name: imdb_movie_application
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  flutter:
    sdk: flutter
  flutter_pull_to_refresh: ^1.0.1
  octo_image: ^1.0.0+1
  provider: ^6.0.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Light.ttf
          weight: 200
        - asset: fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: fonts/Montserrat-Bold.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-Black.ttf
          weight: 100

  assets:
    - assets/

